package edu.towson;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;

import javax.swing.JOptionPane;

/**
 *
 * @author williamsmith
 */
public class AddInstructor extends javax.swing.JPanel {

    private Model model = new Model();
    Model.ModelObserver mObserver = model.new ModelObserver();
    /**
     * Creates new form AddAdvisor
     */
    public AddInstructor() {
        initComponents();
    }
    
    public AddInstructor(Model model) {
        super(new BorderLayout());
        this.model = model;
        model.addObserver(mObserver);
        
        initComponents();
        
        //Using a linked list here so it can grow dynamically - array could have empty spaces that might show up in combo box
        LinkedList<String> list = new LinkedList();
        String sql = "SELECT DISTINCT Dept_Name From DEPARTMENT";
        try (Connection conn = Main.connect();
                Statement stmt = conn.createStatement()){
        	ResultSet rs = stmt.executeQuery(sql);
        	while (rs.next()) {
        		list.add(rs.getString("Dept_Name"));
        	}
        } catch (SQLException e) {
        }
        
        String[] fromLinkedList = list.toArray(new String[list.size()]);
        addInst_addDeptNumCB.setModel(new javax.swing.DefaultComboBoxModel<>(fromLinkedList));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adad_addInstrctrBtn = new javax.swing.JButton();
        adad_mainMenuBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addInst_instIdNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addInst_fname = new javax.swing.JTextField();
        addInst_mname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addInst_lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addInst_addDeptNumCB = new javax.swing.JComboBox<>();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add an Instructor");

        adad_addInstrctrBtn.setForeground(new java.awt.Color(206, 17, 38));
        adad_addInstrctrBtn.setText("Add Instructor");
        adad_addInstrctrBtn.setToolTipText("");
        adad_addInstrctrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adad_addInstructorBtnActionPerformed(evt);
            }
        });

        adad_mainMenuBtn.setForeground(new java.awt.Color(206, 17, 38));
        adad_mainMenuBtn.setText("Main Menu");
        adad_mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adad_mainMenuBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter instructor id#");
        jLabel2.setToolTipText("");

        addInst_instIdNum.setToolTipText("Enter instructor ID#");

        jLabel3.setText("Enter first name");

        jLabel4.setText("Enter middle name");

        addInst_fname.setToolTipText("Enter first name");

        addInst_mname.setToolTipText("Add middle name");

        jLabel5.setText("Enter last name");

        addInst_lname.setToolTipText("Enter lname");

        jLabel6.setText("Select dept#");

        addInst_addDeptNumCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addInst_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addInst_addDeptNumCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 135, Short.MAX_VALUE)
                                .addComponent(adad_mainMenuBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adad_addInstrctrBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addInst_instIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel6))
                                            .addComponent(addInst_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(addInst_mname))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInst_instIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addInst_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addInst_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addInst_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addInst_addDeptNumCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adad_addInstrctrBtn)
                    .addComponent(adad_mainMenuBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adad_mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adad_mainMenuBtnActionPerformed
        String cmd = evt.getActionCommand();
            if ("Main Menu".equals(cmd)) {
                model.returnToMainMenu();
            }
    }//GEN-LAST:event_adad_mainMenuBtnActionPerformed

    private void adad_addInstructorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adad_addInstructorBtnActionPerformed
        // TODO Navya this is the button where we'll write the form contents to the database
    	boolean sIdIsValid = checkInstructorId();
    	boolean showErrorMsg = false;
        String errorMessage = "";  
        int dep_num=0;
        String deptsql = "SELECT Dept_Num From DEPARTMENT WHERE Dept_Name = ?";
        try (Connection conn = Main.connect(); PreparedStatement stmt = conn.prepareStatement(deptsql)) {
			stmt.setString(1, String.valueOf(addInst_addDeptNumCB.getSelectedItem()));
			ResultSet rs = stmt.executeQuery();
        	if (rs.next()) {
        	 dep_num=rs.getInt("Dept_Num");
        	}
        } catch (SQLException e) {
        }
        String sql = "INSERT INTO INSTRUCTOR(Instructor_Id, First, Middle, Last, Dept_Num) VALUES(?,?,?,?,?)";
        if(sIdIsValid==true){
            try (Connection conn = Main.connect();
                PreparedStatement pstmt = conn.prepareStatement(sql)){
                pstmt.setString(1, addInst_instIdNum.getText());
                pstmt.setString(2, addInst_fname.getText());
                pstmt.setString(3, addInst_mname.getText());
                pstmt.setString(4, addInst_lname.getText());
                pstmt.setInt(5, dep_num);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfully added instructor");
                addInst_instIdNum.setText("");
                addInst_fname.setText("");
                addInst_mname.setText("");
                addInst_lname.setText("");
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
        }
             
        else {
            if(sIdIsValid == false){
                errorMessage = errorMessage + "instructor id already exist \n";
                showErrorMsg = true;
            }
        }
        if(showErrorMsg == true){
            JOptionPane.showMessageDialog(null, errorMessage);
        }
    }//GEN-LAST:event_adad_addInstructorBtnActionPerformed

    private boolean checkInstructorId() {
		boolean result = false;

		String sql = "SELECT * From INSTRUCTOR WHERE Instructor_Id = ?";
		try (Connection conn = Main.connect(); PreparedStatement stmt = conn.prepareStatement(sql)) {
			stmt.setString(1, addInst_instIdNum.getText());
			ResultSet rs = stmt.executeQuery();

			if (rs.next()) {
				result = false;
			} else {
				result = true;
			}

		} catch (SQLException e) {

		}
		return result;

	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adad_addInstrctrBtn;
    private javax.swing.JButton adad_mainMenuBtn;
    private javax.swing.JComboBox<String> addInst_addDeptNumCB;
    private javax.swing.JTextField addInst_fname;
    private javax.swing.JTextField addInst_instIdNum;
    private javax.swing.JTextField addInst_lname;
    private javax.swing.JTextField addInst_mname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
