package edu.towson;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author williamsmith
 */
public class AddStudent extends javax.swing.JPanel {

    private Model model = new Model();
    Model.ModelObserver mObserver = model.new ModelObserver();
    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }
    
    public AddStudent(Model model) {
        super(new BorderLayout());
        this.model = model;
        model.addObserver(mObserver);
        initComponents();
    }

    //TODO: Wire up the add student button to write to a new db record
    
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        as_firstName = new javax.swing.JTextField();
        as_middleName = new javax.swing.JTextField();
        as_lastName = new javax.swing.JTextField();
        as_sIdNum = new javax.swing.JTextField();
        as_permAddress = new javax.swing.JTextField();
        as_currentAddress = new javax.swing.JTextField();
        as_male = new javax.swing.JRadioButton();
        as_female = new javax.swing.JRadioButton();
        as_dob = new javax.swing.JFormattedTextField();
        as_email = new javax.swing.JTextField();
        as_grantAuth = new javax.swing.JTextField();
        as_addStudentBtn = new javax.swing.JButton();
        as_mainMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        as_addSSNFormatted = new javax.swing.JFormattedTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add a Student");

        as_firstName.setToolTipText("Enter first name");

        as_middleName.setToolTipText("Enter middle name");

        as_lastName.setToolTipText("Enter last name");

        as_sIdNum.setToolTipText("Enter student id#");

        as_permAddress.setToolTipText("Enter the student's permanent address");

        as_currentAddress.setToolTipText("Enter student's current address");

        buttonGroup1.add(as_male);
        as_male.setText("M");
        as_male.setToolTipText("");

        buttonGroup1.add(as_female);
        as_female.setText("F");

        as_dob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        as_dob.setToolTipText("Format YYYY-MM-DD");

        as_email.setToolTipText("Enter student's email address");

        as_grantAuth.setToolTipText("Enter grant auth# if applicable");

        as_addStudentBtn.setForeground(new java.awt.Color(206, 17, 38));
        as_addStudentBtn.setText("Add Student");
        as_addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as_addStudentBtnActionPerformed(evt);
            }
        });

        as_mainMenu.setForeground(new java.awt.Color(206, 17, 38));
        as_mainMenu.setText("Main Menu");
        as_mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtnToMainMenuBtn(evt);
            }
        });

        jLabel2.setText("Enter first name");

        jLabel3.setText("Enter middle name");

        jLabel4.setText("Enter last name");

        jLabel5.setText("Enter SSN");

        jLabel6.setText("Enter student id#");

        jLabel7.setText("Enter DOB");

        jLabel8.setText("Enter perm address");

        jLabel9.setText("Enter current address");

        jLabel10.setText("Enter email address");

        jLabel11.setText("Grant auth#");

        jLabel13.setText("Select gender");

        try {
            as_addSSNFormatted.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        as_addSSNFormatted.setToolTipText("Enter only digits of SSN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(as_female)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(as_mainMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(as_addStudentBtn))
                            .addComponent(as_email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(as_permAddress)
                            .addComponent(as_currentAddress)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(as_addSSNFormatted)
                                        .addGap(187, 187, 187))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(as_male)
                                        .addGap(12, 246, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(as_sIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addComponent(as_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(as_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(as_middleName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7))
                                    .addComponent(as_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(as_grantAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(as_middleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(as_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as_sIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(as_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(as_addSSNFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(as_permAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(as_currentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(as_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(as_grantAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(as_male, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as_female)
                    .addComponent(as_addStudentBtn)
                    .addComponent(as_mainMenu))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RtnToMainMenuBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtnToMainMenuBtn
        String cmd = evt.getActionCommand();
            if ("Main Menu".equals(cmd)) {
                model.returnToMainMenu();
            }
    }//GEN-LAST:event_RtnToMainMenuBtn


    

	private void as_addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_as_addStudentBtnActionPerformed
		// TODO Navya could you add logic here to perform the write of the form
		// info to the database?
		boolean sSSNIsValid = checkSSN();
		boolean sIdIsValid = checkSId();
		boolean showErrorMsg = false;
		String errorMessage = "";
		String sql = "INSERT INTO STUDENT(FName , Middle , LName , SSN , Sid , Perm_address, Current_adress,Grant_Auth,Email_id,Sex,DOB ) "
				+ "VALUES(?,?,?,?,?,?,?,?,?,?,?)";
		if (sIdIsValid == true && sSSNIsValid == true) {
			try (Connection conn = Main.connect(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
				pstmt.setString(1, as_firstName.getText());
				pstmt.setString(2, as_middleName.getText());
				pstmt.setString(3, as_lastName.getText());
				pstmt.setString(4, as_addSSNFormatted.getText());
				pstmt.setString(5, as_sIdNum.getText());
				pstmt.setString(6, as_permAddress.getText());
				pstmt.setString(7, as_currentAddress.getText());
				pstmt.setString(8, as_grantAuth.getText());
				pstmt.setString(9, as_email.getText());
				
				if(as_male.isSelected()){
					pstmt.setString(10, as_male.getText());	
				}
				else {
					pstmt.setString(10, as_female.getText());
				}
				pstmt.setString(11, as_dob.getText());
				pstmt.executeUpdate();
				JOptionPane.showMessageDialog(null, "Successfully added student");
				as_firstName.setText("");
				as_middleName.setText("");
				as_lastName.setText("");
				as_addSSNFormatted.setText("");
				as_sIdNum.setText("");
				as_permAddress.setText("");
				as_currentAddress.setText("");
				as_grantAuth.setText("");
				as_email.setText("");
				as_dob.setText("");
			} catch (SQLException e) {
				System.out.println(e.getMessage());
			}
		} else {
			if (sSSNIsValid == false) {
				errorMessage = errorMessage + "Duplicate SSN\n";
				showErrorMsg = true;
			}
			if (sIdIsValid == false) {
				errorMessage = errorMessage + "Please enter a valid student id number\n";
				showErrorMsg = true;
			}
		}
		if (showErrorMsg == true) {
			JOptionPane.showMessageDialog(null, errorMessage);
		}
	}// GEN-LAST:event_as_addStudentBtnActionPerformed

	private boolean checkSSN() {
		boolean result = false;

		String sql = "SELECT * From STUDENT WHERE SSN = ?";
		try (Connection conn = Main.connect(); PreparedStatement stmt = conn.prepareStatement(sql)) {
			stmt.setString(1, as_addSSNFormatted.getText());
			ResultSet rs = stmt.executeQuery();

			if (rs.next()) {
				// JOptionPane.showMessageDialog(null, "Enter Valid Student
				// Id");
				result = false;
			} else {
				result = true;
			}

		} catch (SQLException e) {

		}
		return result;
	}

	private boolean checkSId() {
		boolean result = false;

		String sql = "SELECT * From IDCARD WHERE Id_No = ?";
		try (Connection conn = Main.connect(); PreparedStatement stmt = conn.prepareStatement(sql)) {
			stmt.setString(1, as_sIdNum.getText());
			ResultSet rs = stmt.executeQuery();

			if (!rs.next()) {
				// JOptionPane.showMessageDialog(null, "Enter Valid Student
				// Id");
				result = false;
			} else {
				result = true;
			}

		} catch (SQLException e) {

		}
		return result;

	}
   
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField as_addSSNFormatted;
    private javax.swing.JButton as_addStudentBtn;
    private javax.swing.JTextField as_currentAddress;
    private javax.swing.JFormattedTextField as_dob;
    private javax.swing.JTextField as_email;
    private javax.swing.JRadioButton as_female;
    private javax.swing.JTextField as_firstName;
    private javax.swing.JTextField as_grantAuth;
    private javax.swing.JTextField as_lastName;
    private javax.swing.JButton as_mainMenu;
    private javax.swing.JRadioButton as_male;
    private javax.swing.JTextField as_middleName;
    private javax.swing.JTextField as_permAddress;
    private javax.swing.JTextField as_sIdNum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
