package edu.towson;

import java.awt.BorderLayout;

/**
 *
 * @author williamsmith
 */
public class SearchMenu extends javax.swing.JPanel {

    private Model model = new Model();
    Model.ModelObserver mObserver = model.new ModelObserver();
    /**
     * Creates new form SearchMenu
     */
    public SearchMenu() {
        initComponents();
    }
    
    public SearchMenu(Model model) {
        super(new BorderLayout());
        this.model = model;
        model.addObserver(mObserver);
        
        initComponents();
        String[] queryList = new String[]{" ", "View all students", "View all instructors", "", "", 
            ""};
        querySelectCB.setModel(new javax.swing.DefaultComboBoxModel<>(queryList));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sm_mainMenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        querySelectCB = new javax.swing.JComboBox<>();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Menu");

        sm_mainMenu.setForeground(new java.awt.Color(206, 17, 38));
        sm_mainMenu.setText("Main Menu");
        sm_mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtnToMainMenuBtn(evt);
            }
        });

        jButton1.setText("Test ResultsTable");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        querySelectCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        querySelectCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                querySelectCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(sm_mainMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(querySelectCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(querySelectCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sm_mainMenu)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RtnToMainMenuBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtnToMainMenuBtn
        String cmd = evt.getActionCommand();
            if ("Main Menu".equals(cmd)) {
                model.returnToMainMenu();
            }
    }//GEN-LAST:event_RtnToMainMenuBtn

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cmd = evt.getActionCommand();
            if ("Test ResultsTable".equals(cmd)) {
                model.goToQueryResult(TableList.STUDENT);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void querySelectCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_querySelectCBActionPerformed
        int selection = querySelectCB.getSelectedIndex();
        switch(selection){
            case 1:
                //DatabaseView.setItem(TableList.STUDENT);
                model.goToQueryResult(TableList.STUDENT);
                break;
            case 2:
                //DatabaseView.setItem(TableList.INSTRUCTOR);
                model.goToQueryResult(TableList.INSTRUCTOR);
                break;
            case 3:
                //TODO
                break;
            case 4:
                //TODO
                break;
            case 5:
                //TODO
                break;
        }
    }//GEN-LAST:event_querySelectCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> querySelectCB;
    private javax.swing.JButton sm_mainMenu;
    // End of variables declaration//GEN-END:variables
}
